### ISSUE TITLE
Error with PEPPAN_parser related to the captured group

### ISSUE THREAD

**Issue by matrs** [zheminzhou/PEPPA#18]
Hello,
Thanks for this free software.  
I ran `PEPPAN 1.0.6` successfully, but when I try to run the parser I got the following error, related to the captured group:

`PEPPAN_parser -g blau_all.PEPPAN_head100.gff `

```terminal
Traceback (most recent call last):
  File "/home/mibu/miniconda3/envs/bif2020/bin/PEPPAN_parser", line 8, in <module>
    sys.exit(PEPPA_parser())
  File "/home/mibu/miniconda3/envs/bif2020/lib/python3.8/site-packages/PEPPAN/PEPPAN_parser.py", line 206, in PEPPA_parser
    ortho = getOrtho(param.gff, param.pseudogene)
  File "/home/mibu/miniconda3/envs/bif2020/lib/python3.8/site-packages/PEPPAN/PEPPAN_parser.py", line 58, in getOrtho
    orthos = [ [o, int(aId) if aId.isdigit() else -1] for o, aId in [ o.split(':')[1:3] for o in ortho.split(',') ]]
  File "/home/mibu/miniconda3/envs/bif2020/lib/python3.8/site-packages/PEPPAN/PEPPAN_parser.py", line 58, in <listcomp>
    orthos = [ [o, int(aId) if aId.isdigit() else -1] for o, aId in [ o.split(':')[1:3] for o in ortho.split(',') ]]
ValueError: not enough values to unpack (expected 2, got 1)
````

`blau_all.PEPPAN_head100.gff`  contains the first 100 lines from the output gff from PEPPAN. I'm attaching it in case you want to test it (has `.txt`  file type because github complains other way):
[blau_all.PEPPAN_head100.gff.txt](https://github.com/zheminzhou/PEPPAN/files/5837389/blau_all.PEPPAN_head100.gff.txt)

Hope this is enough information, 

Regards

Jose Luis

**Comment by Detective-moneill** [comment]
Hello. I am getting the same error. Did you ever get a response? Thanks!

**Comment by matrs** [comment]
> Hello. I am getting the same error. Did you ever get a response? Thanks!

Hello, 
I didn't receive a response and I really don't remember if I fix it in someway, because I did run it sucessfully a few times.
