### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by verylili** [zheminzhou/PEPPA#28]
Hi, 
I was running PEPPAN on ~1700 E. coli genomes. I met an error as follows:
Traceback (most recent call last):
  File "/home/LL/miniconda3/envs/PEPPAN/bin/PEPPAN", line 8, in <module>
    sys.exit(ortho())
             ^^^^^^^
  File "/home/LL/miniconda3/envs/PEPPAN/lib/python3.11/site-packages/PEPPAN/PEPPAN.py", line 1916, in ortho
    filt_genes(tab_conn, np.load(params['self_bsn'], allow_pickle=True), params['global'], params['map_bsn']+'.conflicts.npz', priorities, gene_scores, encodes)
  File "/home/LL/miniconda3/envs/PEPPAN/lib/python3.11/site-packages/PEPPAN/PEPPAN.py", line 732, in filt_genes
    mat_out.append([pangene_name, gene_name, min_rank, mat])
  File "<string>", line 2, in append
  File "/home/LL/miniconda3/envs/PEPPAN/lib/python3.11/multiprocessing/managers.py", line 821, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/home/LL/miniconda3/envs/PEPPAN/lib/python3.11/multiprocessing/connection.py", line 205, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/LL/miniconda3/envs/PEPPAN/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/home/LL/miniconda3/envs/PEPPAN/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

**Comment by verylili** [comment]
This error occurred on a server, not a personal computer. And I met the error when the number of genomes is large.
